### ISSUE TITLE
Cannot find module '../build/Release/canvas.node'

### ISSUE THREAD

**Issue by ulysserevient** [Keristero/voxel-map-image-combiner#1]
Hi,
I'm trying your program, but encounter this error :
`pkg/prelude/bootstrap.js:1176
      throw error;
      ^

Error: Cannot find module '../build/Release/canvas.node'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1278:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\snapshot\QuotroMap\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)`

How can I correct this error ?
Thx.

**Comment by Keristero** [comment]
Hi, I have not run this script in a long time. I'll see if I can get it working

**Comment by Keristero** [comment]
Okay, I switched canvas libraries to another one because I could not for the life of me get the old one working. Unfortunately I could not package the new library into an exe, so you will need to install node.js and run `npm install` before running the script.
